// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "wy-goframe-admin/internal/logic/casbin"
	_ "wy-goframe-admin/internal/logic/login"
	_ "wy-goframe-admin/internal/logic/mm"
	_ "wy-goframe-admin/internal/logic/session"
)
