// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUser is the golang structure of table sys_user for DAO operations like Where/Data.
type SysUser struct {
	g.Meta   `orm:"table:sys_user, do:true"`
	Id       interface{} //
	Userid   interface{} //
	Username interface{} //
	Password interface{} //
	Email    interface{} //
	Roles    interface{} //
	Enable   interface{} //
	CreateAt *gtime.Time //
	UpdateAt *gtime.Time //
	Remark   interface{} //
}
