// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysApi is the golang structure of table sys_api for DAO operations like Where/Data.
type SysApi struct {
	g.Meta      `orm:"table:sys_api, do:true"`
	Id          interface{} //
	Path        interface{} // api路径
	Description interface{} // api中文描述
	ApiGroup    interface{} // api组
	Method      interface{} // 方法
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
	DeletedAt   *gtime.Time //
}
