// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"wy-goframe-admin/internal/model"

	"github.com/gogf/gf/v2/net/ghttp"
)

type (
	IAuditLog interface {
		Save(r *ghttp.Request) (err error)
		Page(ctx context.Context, in model.AuditLogPageInput) (out []*model.AuditLogPageOutput, total int, err error)
	}
)

var (
	localAuditLog IAuditLog
)

func AuditLog() IAuditLog {
	if localAuditLog == nil {
		panic("implement not found for interface IAuditLog, forgot register?")
	}
	return localAuditLog
}

func RegisterAuditLog(i IAuditLog) {
	localAuditLog = i
}
