// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"wy-goframe-admin/internal/model"

	"github.com/gogf/gf/v2/net/ghttp"
)

type (
	ICasbin interface {
		RoleCheck(r *ghttp.Request)
		RuleSave(ctx context.Context, in model.CasbinRuleSaveInput) (err error)
		RulePage(ctx context.Context, in model.CasbinRulePageInput) (out []*model.CasbinRulePageOutput, total int, err error)
		RuleDelete(ctx context.Context, in model.CasbinRuleDeleteInput) (err error)
	}
)

var (
	localCasbin ICasbin
)

func Casbin() ICasbin {
	if localCasbin == nil {
		panic("implement not found for interface ICasbin, forgot register?")
	}
	return localCasbin
}

func RegisterCasbin(i ICasbin) {
	localCasbin = i
}
