// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"wy-goframe-admin/internal/model"

	jwt "github.com/gogf/gf-jwt/v2"
)

type (
	ILogin interface {
		Auth() *jwt.GfJWTMiddleware
		LoginCode(ctx context.Context) (Data *model.LoginCodeOutput, err error)
	}
)

var (
	localLogin ILogin
)

func Login() ILogin {
	if localLogin == nil {
		panic("implement not found for interface ILogin, forgot register?")
	}
	return localLogin
}

func RegisterLogin(i ILogin) {
	localLogin = i
}
