// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"github.com/gogf/gf/v2/net/ghttp"
)

type (
	IMiddelware interface {
		CORS(r *ghttp.Request)
		Auth(r *ghttp.Request)
		Session(r *ghttp.Request)
		Casbin(r *ghttp.Request)
		AuditLog(r *ghttp.Request)
	}
)

var (
	localMiddelware IMiddelware
)

func Middelware() IMiddelware {
	if localMiddelware == nil {
		panic("implement not found for interface IMiddelware, forgot register?")
	}
	return localMiddelware
}

func RegisterMiddelware(i IMiddelware) {
	localMiddelware = i
}
