// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"github.com/gogf/gf/v2/net/ghttp"
)

type (
	IMm interface {
		CORS(r *ghttp.Request)
		Auth(r *ghttp.Request)
		Session(r *ghttp.Request)
		Casbin(r *ghttp.Request)
	}
)

var (
	localMm IMm
)

func Mm() IMm {
	if localMm == nil {
		panic("implement not found for interface IMm, forgot register?")
	}
	return localMm
}

func RegisterMm(i IMm) {
	localMm = i
}
