// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"wy-goframe-admin/internal/model"
)

type (
	ISysRole interface {
		RoleSave(ctx context.Context, in model.SysRoleSaveInput) (err error)
		RolePage(ctx context.Context, in model.SysRolePageInput) (out []*model.SysRolePageOutput, total int, err error)
		RoleDelete(ctx context.Context, in model.SysRoleDeleteInput) (err error)
		GetAllApis(ctx context.Context, in model.SysRoleAllApisInput) (out *model.SysRoleAllApisOutput, err error)
		RoleHasApis(ctx context.Context, in model.SysRoleHasApisInput) (out *model.SysRoleHasApisOutput, err error)
		RoleList(ctx context.Context, in model.SysRoleListInput) (out []*model.SysRoleListOutput, err error)
	}
)

var (
	localSysRole ISysRole
)

func SysRole() ISysRole {
	if localSysRole == nil {
		panic("implement not found for interface ISysRole, forgot register?")
	}
	return localSysRole
}

func RegisterSysRole(i ISysRole) {
	localSysRole = i
}
