// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"wy-goframe-admin/internal/model"
)

type (
	ISysApi interface {
		ApiSave(ctx context.Context, in model.SysApiSaveInput) (err error)
		ApiPage(ctx context.Context, in model.SysApiPageInput) (out []*model.SysApiPageOutput, total int, err error)
		ApiDelete(ctx context.Context, in model.SysApiDeleteInput) (err error)
		ApiGroupsList(ctx context.Context, in model.SysApiGroupsListInput) (out []*model.SysApiGroupsListOutput, err error)
	}
)

var (
	localSysApi ISysApi
)

func SysApi() ISysApi {
	if localSysApi == nil {
		panic("implement not found for interface ISysApi, forgot register?")
	}
	return localSysApi
}

func RegisterSysApi(i ISysApi) {
	localSysApi = i
}
