// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"wy-goframe-admin/internal/model"
)

type (
	IUser interface {
		UserCheck(ctx context.Context, in model.UserLoginInput) (userMap map[string]interface{})
		UserCreate(ctx context.Context, in model.UserCreateInput) (err error)
		UserUpdate(ctx context.Context, in model.UserUpdateInput) (err error)
		UserResetPass(ctx context.Context, in model.UserResetPassInput) (err error)
		UserPage(ctx context.Context, in model.UserPageInput) (out []*model.UserPageOutput, total int, err error)
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
