// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wy-goframe-admin/internal/dao/internal"
)

// internalAuditlogDao is internal type for wrapping internal DAO implements.
type internalAuditlogDao = *internal.AuditlogDao

// auditlogDao is the data access object for table auditlog.
// You can define custom methods on it to extend its functionality as you wish.
type auditlogDao struct {
	internalAuditlogDao
}

var (
	// Auditlog is globally public accessible object for table auditlog operations.
	Auditlog = auditlogDao{
		internal.NewAuditlogDao(),
	}
)

// Fill with you ideas below.
