// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AuditLog is the golang structure for table audit_log.
type AuditLog struct {
	Id           int         `json:"id"           description:""`
	TraceId      string      `json:"traceId"      description:""`
	Username     string      `json:"username"     description:""`
	Ip           string      `json:"ip"           description:""`
	Path         string      `json:"path"         description:""`
	Method       string      `json:"method"       description:""`
	Params       string      `json:"params"       description:""`
	HttpCode     int         `json:"httpCode"     description:""`
	ResponseTime string      `json:"responseTime" description:""`
	CreateAt     *gtime.Time `json:"createAt"     description:""`
}
