// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysApi is the golang structure for table sys_api.
type SysApi struct {
	Id          int64       `json:"id"          description:""`
	Path        string      `json:"path"        description:"api路径"`
	Method      string      `json:"method"      description:"方法"`
	ApiGroup    string      `json:"apiGroup"    description:"api组"`
	Description string      `json:"description" description:"api中文描述"`
	CreateAt    *gtime.Time `json:"createAt"    description:""`
	UpdateAt    *gtime.Time `json:"updateAt"    description:""`
}
