// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysApi is the golang structure for table sys_api.
type SysApi struct {
	Id          int64       `json:"id"          description:""`
	Path        string      `json:"path"        description:"api路径"`
	Description string      `json:"description" description:"api中文描述"`
	ApiGroup    string      `json:"apiGroup"    description:"api组"`
	Method      string      `json:"method"      description:"方法"`
	CreatedAt   *gtime.Time `json:"createdAt"   description:""`
	UpdatedAt   *gtime.Time `json:"updatedAt"   description:""`
	DeletedAt   *gtime.Time `json:"deletedAt"   description:""`
}
