// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysRole is the golang structure for table sys_role.
type SysRole struct {
	Id          int         `json:"id"          description:""`
	Role        string      `json:"role"        description:""`
	Description string      `json:"description" description:""`
	CreateAt    *gtime.Time `json:"createAt"    description:""`
	UpdateAt    *gtime.Time `json:"updateAt"    description:""`
}
